### ISSUE TITLE
The logo is invisible

### ISSUE THREAD

**Issue by coolaj86** [nme077/card_app#14]
```txt
src="client/images/White on Transparent.png"
```

Dark mode is for dweebs. Real men bask in the light of glory.

Seriously though, I can't stand dark mode. GitHub is _not_ one of the few applications that do it well IMNSHO.

**Comment by coolaj86** [comment]
I wonder if GitHub supports the `<picture>` tag in readmes. And I wonder if the `<picture>` tag has a way to select dark mode. Seems like it should.

**Comment by nme077** [comment]
Fixed this issue, for now I changed the color of the logo to work in light or dark. It looks like there is a lot of conversation online about github adding support for checking whether the user in light or dark mode, but alas there is no way to do so at the moment... Thanks @coolaj86
